Install Ubuntu
acm-uiuc/til pull request #4
Opened 2017-04-18 00:25 UTC by theishshah

Issue #2

2017-04-18 00:30 UTC, theishshah commented
Travis won't accept bootloader and is throwing me a spelling error

2017-04-18 17:33 UTC, narendasan commented on _til/linux/install-ubuntu.md
> +* Choose to install 3rd party non-free items (Flash, MP3, etc. I usually select yes as it makes the user experience much easier)
Comment here on how free is means free as in libre and not something you have to pay for

2017-04-18 17:33 UTC, narendasan commented on _til/linux/install-ubuntu.md
> +* Create a user and hostname
note hostname == name of your computer

2017-04-18 17:39 UTC, narendasan requested changes

2017-04-18 17:39 UTC, narendasan commented on _til/linux/install-ubuntu.md
> +* Choose to install 3rd party non-free items (Flash, MP3, etc. I usually select yes as it makes the user experience much easier)
make a note here that this is free as in libre and not something you need to pay for

2017-04-18 17:39 UTC, narendasan commented on _til/linux/install-ubuntu.md
> +* Partition the disk (See below)
Manual disk partitioning is typically not required. There are options to install over any existing OS (which will also apply to no OS) and to install along side the existing OS. This should be recommended unless more control is needed

2017-04-18 17:39 UTC, narendasan commented on _til/linux/install-ubuntu.md
> +* Create a user and hostname
note that the hostname == name of you computer

2017-04-18 17:39 UTC, narendasan commented on _til/linux/install-ubuntu.md
> +## Partitions
include:
> Partitioning is required if you want more complicated layouts for you storage i.e you want all your documents on one disk but the os on another, or you are dealing with a volatile system and need to insure exact partition layouts.

2017-04-18 17:39 UTC, narendasan commented on _til/linux/install-ubuntu.md
> +
Instructions on how to create a boot disk pls

2017-04-25 19:38 UTC, narendasan commented
@theishshah, can you you address these issues?

2017-04-25 19:58 UTC, theishshah commented
@narendasan updated!

2017-04-25 20:11 UTC, theishshah commented
@narendasan travis is failing over bootable, iso os dropdown and whatnot. no actual spelling errors

2017-04-25 20:49 UTC, narendasan commented
@theishshah  add them to dictionary.yml

2017-04-25 20:54 UTC, narendasan requested changes

2017-04-25 20:54 UTC, narendasan commented on _til/linux/install-ubuntu.md
> +## Creating bootable media
Add instructions for Ubuntu (use startup disk creator) and Mac ideally

2017-04-25 20:54 UTC, narendasan commented on _til/linux/install-ubuntu.md
> +* Partition the disk (See below. Manual partitioning is generally not required as the installer will offer both dual-boot options and full replacement automatically)
Change this to: Select how to install the OS (either overwrite the disk, install along side another OS or a more complicated layout (LINK here)) 

Prioritize the easy stuff, it makes things more accessible

2017-04-25 20:54 UTC, narendasan commented on _til/linux/install-ubuntu.md
> +## Dual Booting
Make some of this a sub section of partitioning or something and the other about the bootloader

2017-05-01 04:50 UTC, narendasan commented
@theishshah

2017-05-15 03:33 UTC, narendasan commented
@theishshah

2017-05-18 21:32 UTC, closed without merging